### ISSUE TITLE
[Feature Request] Training Procedure

### ISSUE THREAD

**Issue by nanton96** [jenniening/deltaVinaXGB#1]
After taking a look at your code I realised that you only provide inference functionality with pre-trained models.

Are you planning on releasing code with the implementation of your training procedure, including pre-processing on the PDBbind database for the construction of the training/validation sets?

I am asking this because I would like to train your model with additional data.

**Comment by jenniening** [comment]
Hi Nick, thanks for your question. 
Yes, the major part of this repo is the pre-trained model since we built this scoring function as a tool and hope user can directly apply it in protein-ligand binding affinity prediction. 
For the data preprocessing scripts, you can find it in "support" folder. 
In terms of training script, we actually used Python version of XGBoost package downloaded from its official website (https://xgboost.readthedocs.io/en/latest/python/index.html), and described the training protocol in our paper. Nothing special. If you want to train our model with additional data, I recommended you to do the grid search to find the hyperparameters which fit the new datasets. Also, we provided all the feature calculations in our current repo, so you can directly generated all necessary features for model development. 
Hope this answer is helpful.
