### ISSUE TITLE
Vina: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hypnopump** [jenniening/deltaVinaXGB#3]
I'm trying to run the tests on a WSL (Ubuntu 18.04) and the custom Vina crashes everytime. Any ideas of what might be causing the problem?

**Comment by hypnopump** [comment]
```
$ $VINADIR/vina --receptor 2al5_protein.pdbqt --ligand  2al5_ligand_rename.pdbqt

> Segmentation fault (core dumped)
```

**Comment by jenniening** [comment]
Hi Eric, thanks for your question. 
I'm not very sure about this error since Vina is not developed by us and I'm not very familiar with WSL (Ubuntu 18.04) system . My recommendation is to first make sure you are using the right version of Vina for your system. Second is to search solving method in Vina community (smina is a fork of Vina, so you can also take a look at the smina package: https://github.com/mwojcikowski/smina). Recently with the help from other contributor, we also support package installation with Docker, may be you can also try that. 
Hope this helps.

**Comment by hypnopump** [comment]
I've switched to macOS and it seems to work. Perhaps it has something to do with the WSL OS... I don't know what the exact issue is for now, but if i figure it out I'll come back to post the reason here.

**Comment by hypnopump** [comment]
btw, is the jl7003@nyu.edu email address active?

**Comment by jenniening** [comment]
Since we already contacted through email, I'm going to close this issue. Thanks!
